// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSGOU_0-HKobAyHkLAHCRZxuMymO17WFA',
    appId: '1:833597435439:web:e0cff4194a30cd20f0a0da',
    messagingSenderId: '833597435439',
    projectId: 'fikraty',
    authDomain: 'fikraty.firebaseapp.com',
    storageBucket: 'fikraty.firebasestorage.app',
    measurementId: 'G-6F89TYNR7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4AAAYWnaOu4ro6JQ4jb533e8nUTw3rD4',
    appId: '1:833597435439:android:a6364033a07e6e57f0a0da',
    messagingSenderId: '833597435439',
    projectId: 'fikraty',
    storageBucket: 'fikraty.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAslcjsnUHJCfhQMFJ4tOa5G0tVeybQ78A',
    appId: '1:833597435439:ios:b35078f629061a9af0a0da',
    messagingSenderId: '833597435439',
    projectId: 'fikraty',
    storageBucket: 'fikraty.firebasestorage.app',
    iosBundleId: 'com.example.depiGraduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAslcjsnUHJCfhQMFJ4tOa5G0tVeybQ78A',
    appId: '1:833597435439:ios:b35078f629061a9af0a0da',
    messagingSenderId: '833597435439',
    projectId: 'fikraty',
    storageBucket: 'fikraty.firebasestorage.app',
    iosBundleId: 'com.example.depiGraduationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSGOU_0-HKobAyHkLAHCRZxuMymO17WFA',
    appId: '1:833597435439:web:a72ce8dd27dcfa76f0a0da',
    messagingSenderId: '833597435439',
    projectId: 'fikraty',
    authDomain: 'fikraty.firebaseapp.com',
    storageBucket: 'fikraty.firebasestorage.app',
    measurementId: 'G-YFXWBL6SJL',
  );
}
